# Generated by Django 3.2.4 on 2021-06-14 14:02

import comensales.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comensal',
            name='comida',
        ),
        migrations.AddField(
            model_name='comensal',
            name='codigo',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(choices=[(comensales.models.enumComidas['DE'], 'Desayuno'), (comensales.models.enumComidas['BR'], 'Brunch'), (comensales.models.enumComidas['AL'], 'Almuerzo'), (comensales.models.enumComidas['ME'], 'Merienda'), (comensales.models.enumComidas['CE'], 'Cena')], max_length=8)),
                ('fecha', models.DateTimeField()),
                ('de_comensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comensales.comensal')),
            ],
        ),
    ]
