# Generated by Django 3.2.4 on 2021-06-14 14:32

import comensales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0002_auto_20210614_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='comida',
        ),
        migrations.AddField(
            model_name='comida',
            name='com',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Brunch', 'Brunch'), ('Almuerzo', 'Almuerzo'), ('Merienda', 'Merienda'), ('Cena', 'Cena')], default=comensales.models.enumComidas['DE'], max_length=8),
        ),
    ]
