# Generated by Django 3.2.4 on 2021-06-14 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0003_auto_20210614_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 15, 2, 27, 710032, tzinfo=utc)),
        ),
    ]
