# Generated by Django 3.2.4 on 2021-06-14 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0004_alter_comida_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
