# Generated by Django 3.1.7 on 2021-06-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0006_auto_20210614_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comensal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comidaactual',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
